import base64
import os
import chainlit as cl
from langchain_core.tools import tool
from langchain_community.tools.tavily_search import TavilySearchResults
from e2b_code_interpreter import Sandbox

_sandbox_instance = None

def get_sandbox():
    global _sandbox_instance
    if _sandbox_instance is None:
        try:
            _sandbox_instance = Sandbox.create()
        except Exception as e:
            print(f"❌ FATAL: Could not create Sandbox: {e}")
            raise e
    return _sandbox_instance

def upload_to_sandbox(local_path: str, remote_path: str):
    """Safely uploads a file."""
    try:
        sb = get_sandbox()
        with open(local_path, "rb") as f:
            sb.files.write(remote_path, f)
        return f"Uploaded {remote_path} to sandbox."
    except Exception as e:
        return f"SYSTEM ERROR: Failed to upload file. Details: {str(e)}"

# --- NEW TOOL: Internet Search ---
@tool
def web_search(query: str):
    """
    Search the internet for up-to-date information (stock prices, documentation, news).
    Use this when you don't know the answer or need real-time data.
    """
    try:
        search_tool = TavilySearchResults(k=3) # Return top 3 results
        results = search_tool.invoke(query)
        
        # Format the results nicely for the LLM
        output = f"Search Results for '{query}':\n"
        for res in results:
            output += f"- {res['content']} (Source: {res['url']})\n"
        return output
        
    except Exception as e:
        return f"SEARCH ERROR: Could not connect to internet. Details: {str(e)}"

# --- EXISTING TOOL: Code Execution (Hardened) ---
@tool
def execute_python(code: str):
    """
    Executes Python code in a secure cloud sandbox.
    Use this to run pandas analysis, generate charts, or do math.
    ALWAYS print the final result so you can see it.
    """
    try:
        sb = get_sandbox()
        execution = sb.run_code(code)
        
        output = ""
        
        # 1. Handle Charts (Images)
        if execution.results:
            for result in execution.results:
                if result.png:
                    try:
                        image_data = base64.b64decode(result.png)
                        cl.run_sync(
                            cl.Message(
                                content="📊 *Chart generated by Agent*",
                                elements=[
                                    cl.Image(name="chart", display="inline", content=image_data, size="large")
                                ]
                            ).send()
                        )
                        output += "[Chart visualized for user]\n"
                    except Exception as img_err:
                        output += f"Warning: Chart generated but failed to display. {img_err}\n"

        # 2. Capture Standard Output & Code Errors
        if execution.logs.stdout:
            output += f"STDOUT: {execution.logs.stdout}\n"
        if execution.logs.stderr:
            output += f"STDERR: {execution.logs.stderr}\n"
        if execution.error:
            output += f"CODE ERROR: {execution.error.name}: {execution.error.value}\n"
            output += f"TRACEBACK: {execution.error.traceback}\n"
                    
        if not output:
            output = "Code executed successfully but returned no output. Did you forget to print()?"
            
        return output

    except Exception as e:
        # Catch SYSTEM errors (API down, network fail) so the agent knows
        return f"SYSTEM ERROR (Sandbox Failed): {str(e)}. You may need to retry."